version: "3"

services:
  
  nginx:
    build:
      context: ./docker/nginx/${NGINX_VERSION}
    ports:
      - 80:8000
    links:
      - phpfpm
      - redis:cache
    volumes:
      - ./magento:/var/www/html
      - ./data/sock:/sock
      - ./data/nginx_log:/var/log/nginx

  phpfpm:
    build:
      context: ./docker/php/${PHP_VERSION}
    links:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker/php/${PHP_VERSION}/.composer:/var/www/.composer
      - ./magento:/var/www/html
      - ./data/phpfpm_log:/var/log
      - ./data/sock:/sock

  redis:
    image: redis:${REDIS_VERSION}
    restart: on-failure:5
    volumes:
      - ./data/redis_data:/data
    expose:
      - 6379

  database:
    image: mariadb:${MARIADB_VERSION}
    env_file: env/db.env
    volumes:
      - ./data/maria_data:/var/lib/mysql
      - ./data/maria_log:/var/log/mysql
    ports:
      - 3306:3306

  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
    volumes:
      - ./data/elastic_data:/usr/share/elasticsearch/data
      - ./data/elastic_log:/var/log/elasticsearch

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    env_file: env/rabbitmq.env
    ports:
      - 15672:15672
      - 5672:5672