version: "3"

services:
  
  nginx:
    image: gusvasquez/magento-nginx:1.19
    ports:
      - 80:8000
      - 443:8443
    volumes:
      - ./magento:/var/www/html
      - sockdata:/sock
      #- log:/var/log/nginx
      - ssldata:/etc/nginx/certs

  phpfpm:
    image: gusvasquez/magento-php:8.1-fpm
    volumes:
      - ~/.composer:/var/www/.composer
      - ./magento:/var/www/html
      #- log:/var/log
      - sockdata:/sock
    extra_hosts:
      - "host.docker.internal:host-gateway"  

  database:
    image: mariadb:10.4
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql
      #- log:/var/log/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:6.2
    restart: on-failure:5
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379

  elasticsearch:
    image: gusvasquez/elasticsearch:7.17.1
    restart: always
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
      #- log:/var/log/elasticsearch

  rabbitmq:
    image: gusvasquez/rabbitmq:3.9
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    env_file: env/rabbitmq.env
    ports:
      - 15672:15672
      - 5672:5672

  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - 1080:1080

volumes:
  sockdata:
  #log:
  ssldata:
  dbdata:
  redisdata:
  elasticdata:
  rabbitmqdata:



